-- VMS eProc Migration
-- Database: eproc_perencanaan
-- Table: tr_history_pengadaan
-- Generated: 2025-07-07 22:58:55

-- Create tr_history_pengadaan table
CREATE TABLE IF NOT EXISTS `tr_history_pengadaan` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `perubahan` varchar(45) NULL,
    `status` varchar(45) NULL,
    `id_pengadaan` int(11) NULL,
    `id_pic` int(11) NULL,
    `id_division` int(11) NULL,
    `id_perencanaan_umum` int(11) NULL,
    `is_writeoff` int(11) NULL,
    `is_planning` int(11) NULL DEFAULT '0',
    `is_perencanaan` int(11) NULL,
    `is_status` int(11) NULL DEFAULT '0',
    `is_approved` int(11) NULL DEFAULT '0',
    `is_approved_hse` int(11) NULL DEFAULT '0',
    `is_reject` int(11) NULL DEFAULT '0',
    `is_multiyear` int(11) NULL,
    `no_pr` varchar(45) NULL,
    `tipe_pr` varchar(45) NULL,
    `pr_lampiran` text NULL,
    `nama_pengadaan` text NULL,
    `tipe_pengadaan` varchar(45) NULL,
    `jenis_pengadaan` varchar(45) NULL,
    `jenis_anggaran` varchar(45) NULL,
    `year_anggaran` text NULL,
    `idr_anggaran` decimal(45,2) NULL,
    `usd_anggaran` decimal(45,2) NULL,
    `hps` int(11) NULL,
    `kak_lampiran` text NULL,
    `lingkup_kerja` text NULL,
    `desc_dokumen` text NULL,
    `metode_pengadaan` varchar(45) NULL,
    `penggolongan_penyedia` varchar(45) NULL,
    `jwpp` text NULL,
    `jwpp_start` date NULL,
    `jwpp_end` date NULL,
    `jwp` text NULL,
    `jwp_start` date NULL,
    `jwp_end` date NULL,
    `penerimaan_pekerjaan` timestamp NULL,
    `desc_metode_pembayaran` text NULL,
    `jenis_kontrak` text NULL,
    `sistem_kontrak` text NULL,
    `desc` text NULL,
    `desc_pengadaan` text NULL,
    `dpt_list` text NULL,
    `desc_reject` text NULL,
    `approved_by` int(11) NULL,
    `date` timestamp NULL,
    `csms` varchar(45) NULL,
    `lampiran_persetujuan` varchar(45) NULL,
    `division` varchar(45) NULL,
    `value` varchar(45) NULL,
    `swakelola` varchar(45) NULL,
    `id_proc_method` varchar(45) NULL,
    `entry_stamp` datetime NULL DEFAULT CURRENT_TIMESTAMP,
    `edit_stamp` datetime NULL,
    `is_cancelled` tinyint(1) NULL DEFAULT '0',
    `del` tinyint(1) NULL DEFAULT '0',
    `desc_batal` text NOT NULL,
    `pejabat_pengadaan_id` int(11) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

