-- VMS eProc Migration
-- Database: eproc
-- Table: ms_procurement
-- Generated: 2025-07-07 22:58:54

-- Create ms_procurement table
CREATE TABLE IF NOT EXISTS `ms_procurement` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `name` varchar(250) NULL,
    `id_division` int(11) NULL,
    `id_fppbj` int(11) NOT NULL,
    `tipe_pengadaan` varchar(255) NOT NULL,
    `no_spmk` varchar(255) NOT NULL,
    `start_spmk_date` date NULL,
    `end_spmk_date` date NULL,
    `spmk_file` varchar(255) NOT NULL,
    `no_cf` varchar(255) NOT NULL,
    `start_cf_date` date NULL,
    `end_cf_date` date NULL,
    `contract_formation_file` varchar(255) NOT NULL,
    `budget_holder` bigint(20) NULL,
    `budget_spender` bigint(20) NULL,
    `entry_stamp` timestamp NULL,
    `edit_stamp` timestamp NULL,
    `budget_source` varchar(20) NULL,
    `no_bahp` varchar(150) NULL,
    `bahp_date` date NULL,
    `id_pejabat_pengadaan` varchar(45) NULL,
    `budget_year` varchar(20) NULL,
    `id_mekanisme` bigint(20) NULL,
    `price_auction` decimal(15,2) NULL,
    `price_auction_kurs` decimal(15,2) NULL,
    `auction_kurs` int(11) NULL,
    `price_nego` decimal(15,2) NULL,
    `price_nego_kurs` decimal(15,2) NULL,
    `nego_kurs` int(11) NULL,
    `status_procurement` tinyint(1) NULL DEFAULT '0',
    `proc_date` timestamp NULL,
    `contract_date` timestamp NULL,
    `del` tinyint(1) NULL DEFAULT '0',
    `auction_type` varchar(20) NULL,
    `work_area` varchar(20) NULL,
    `room` varchar(45) NULL,
    `auction_date` date NULL,
    `auction_duration` int(11) NULL DEFAULT '0',
    `is_started` tinyint(1) NULL DEFAULT '0',
    `is_finished` tinyint(1) NULL DEFAULT '0',
    `is_suspended` tinyint(1) NULL DEFAULT '0',
    `is_fail_auction` tinyint(1) NULL DEFAULT '0',
    `id_sbu` tinyint(1) NULL DEFAULT '0',
    `start_time` datetime NULL,
    `time_limit` datetime NULL,
    `end_hour` time NULL,
    `evaluation_method` varchar(45) NULL,
    `evaluation_method_desc` varchar(45) NULL,
    `idr_value` decimal(15,2) NULL,
    `id_kurs` int(11) NULL,
    `kurs_value` decimal(15,2) NULL,
    `remark` text NULL,
    `jenis` varchar(20) NULL,
    `negosiasi` decimal(15,2) NULL,
    `last_edited` int(11) NULL,
    `is_done` tinyint(1) NULL DEFAULT '0',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

